# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 08:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callback_url', models.URLField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False, editable=False)),
                ('notification_attempts', models.PositiveIntegerField(default=0, editable=False)),
                ('notification_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TxNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notification.Notification')),
                ('tx_id', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]{32}$')])),
                ('confirm_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'confirm count should be greater than 1')])),
            ],
            bases=('notification.notification',),
        ),
    ]
